import psycopg2
from psycopg2 import pool
from psycopg2.extras import execute_values
from typing import Generator
from pgvector.psycopg2 import register_vector
from contextlib import contextmanager
from dotenv import load_dotenv
import os
import numpy as np
load_dotenv()


CONNECTION_STRING2 = os.environ.get("CONNECTION_STRING2")

if not CONNECTION_STRING2:
    raise RuntimeError("CONNECTION_STRING environment variable is not set")

connection_pool =pool.SimpleConnectionPool(
    minconn=1, 
    maxconn=2,
    dsn = CONNECTION_STRING2
)

@contextmanager
def get_connection() -> Generator:
    conn = psycopg2.connect(CONNECTION_STRING2)
    conn.set_client_encoding('UTF8')
    register_vector(conn)
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()
        #print(type(conn))
        #connection_pool.putconn(conn)
    


def create_tables(conn) -> None:
    with conn.cursor() as cur:

        cur.execute("""
            CREATE TABLE IF NOT EXISTS COMPANY (
                company_id  BIGINT          PRIMARY KEY,
                name        VARCHAR(64)     NOT NULL,
                logo        VARCHAR(512)
            );
        """)

        cur.execute("""
            CREATE TABLE IF NOT EXISTS COMPANY_METADATA (
                company_id          BIGINT          PRIMARY KEY,
                name                VARCHAR(64)     NOT NULL,
                industry            VARCHAR(64)     NOT NULL,
                description         TEXT,
                employee_count      INTEGER,
                employee_count_range VARCHAR(64)    NOT NULL,
                CONSTRAINT fk_company_metadata_company
                    FOREIGN KEY (company_id)
                    REFERENCES COMPANY (company_id)
                    ON DELETE CASCADE
            );
        """)

        cur.execute("""
            CREATE TABLE IF NOT EXISTS JOBS (
                job_id      BIGINT          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                title       VARCHAR(256)    NOT NULL,
                location    VARCHAR(64)     NOT NULL,
                salary      VARCHAR(64),
                date_posted DATE,
                job_url     VARCHAR(256)    NOT NULL,
                easy_apply  VARCHAR(256),
                promoted    VARCHAR(256),
                expiry_date DATE,
                company_id  BIGINT          NOT NULL,
                CONSTRAINT fk_jobs_company
                    FOREIGN KEY (company_id)
                    REFERENCES COMPANY (company_id)
                    ON DELETE CASCADE
            );
        """)

        cur.execute("""
            CREATE TABLE IF NOT EXISTS JOB_METADATA (
                job_id              BIGINT          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                applicants_count    VARCHAR(512)    NOT NULL,
                company_apply_url   VARCHAR(512)    NOT NULL,
                job_state           VARCHAR(256)    NOT NULL,
                CONSTRAINT fk_job_metadata_jobs
                    FOREIGN KEY (job_id)
                    REFERENCES JOBS (job_id)
                    ON DELETE CASCADE
            );
        """)

        cur.execute("""
            CREATE TABLE IF NOT EXISTS "USER" (
                user_id         INTEGER         PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
                first_name      VARCHAR(64)     NOT NULL,
                last_name       VARCHAR(64)     NOT NULL,
                email           VARCHAR(128)    UNIQUE,
                password_hash   VARCHAR(255),
                age             INTEGER         NOT NULL
            );
        """)

        cur.execute("""
            CREATE TYPE application_status AS ENUM ('live', 'expired');
        """) if not _enum_exists(cur, 'application_status') else None

        cur.execute("""
            CREATE TABLE IF NOT EXISTS APPLICATION (
                application_id  INTEGER         PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
                status          application_status,
                user_id         INTEGER         NOT NULL,
                job_id          BIGINT          NOT NULL,
                age             INTEGER,
                CONSTRAINT fk_application_user
                    FOREIGN KEY (user_id)
                    REFERENCES "USER" (user_id)
                    ON DELETE CASCADE,
                CONSTRAINT fk_application_job
                    FOREIGN KEY (job_id)
                    REFERENCES JOBS (job_id)
                    ON DELETE CASCADE
            );
        """)

        cur.execute("CREATE EXTENSION IF NOT EXISTS vector;")


        cur.execute("""
            CREATE TABLE IF NOT EXISTS JOB_DESCRIPTION (
                job_id      BIGINT          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                job_description   VARCHAR(24000)  NOT NULL,
                embedding       vector(1536),    
                CONSTRAINT fk_job_description_jobs
                    FOREIGN KEY (job_id)
                    REFERENCES JOBS (job_id)
                    ON DELETE CASCADE
            );
        """)


def _enum_exists(cur, enum_name: str) -> bool:
    cur.execute(
        "SELECT 1 FROM pg_type WHERE typname = %s;",
        (enum_name,)
    )
    return cur.fetchone() is not None

def enable_vector_extension():
    
    conn = psycopg2.connect(CONNECTION_STRING2)
    cur = conn.cursor()
    cur.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    conn.commit()
    cur.close()
    conn.close()

enable_vector_extension() 
with get_connection() as conn :
    create_tables(conn)